version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: frontend_nginx
    ports:
      - "8001:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf